version: "3"

services:
  node0:
    container_name: node0
    image: wasm-n
    ports:
      - "1317:1317"
      - "26656-26657:26656-26657"
      - "9090-9091:9090-9091"
      - "6060:6060"
      - "40783:40783"
    cap_add:
      - SYS_PTRACE
    environment:
      - ID=0
    volumes:
      - type: bind
        source: ./configs/node0/simd
        target: /root/.wasmd
    command: wasmd start --log_level trace
    networks:
      localnet:
        ipv4_address: 192.168.0.1

  node1:
    container_name: node1
    image: wasm-n
    environment:
      - ID=1
    volumes:
      - type: bind
        source: ./configs/node1/simd
        target: /root/.wasmd
    command: wasmd start --mode validator --log_level trace
    networks:
      localnet:
        ipv4_address: 192.168.0.2


  node2:
    container_name: node2
    image: wasm-n
    environment:
      - ID=2
    volumes:
      - type: bind
        source: ./configs/node2/simd
        target: /root/.wasmd
    command: wasmd start --mode validator --log_level trace
    networks:
      localnet:
        ipv4_address: 192.168.0.3

  node3:
    container_name: node3
    image: wasm-n
    environment:
      - ID=3
    volumes:
      - type: bind
        source: ./configs/node3/simd
        target: /root/.wasmd
    command: wasmd start --mode validator --log_level trace
    networks:
      localnet:
        ipv4_address: 192.168.0.4

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.111
